name: Saphmerce
main: org.saphron.saphmerce.Saphmerce
version: 1.0.0
author: Andrei Georgescu
depend: [NSA, Vault, Saphblock]
softdepends: [HolographicDisplays]
description: >
            Saphmerce - Mcmerce
commands:
  shop:
      description: Open the virtual shop
      usage: |
             Usages:
             /shop
  sell:
      description: Sell items without opening the shop
      usage: |
             Usages:
             /sell
             /sell all
  shopAdmin:
      description: Saphmerce admin commands
      usage: |
             Usages:
             /shopAdmin